; Global defaults can go under [*] section (optional)
[*]
ctx-size = 131072
ngl = 99
ctk = q8_0
ctv = q8_0
timeout = 3600
sm = none
mg = 1

; Per-model presets
[qwen3.6-27b-ud-q4-k-xl]
model = /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
jinja = true
chat-template-file = /chat-templates/qwen3.6-v20.jinja
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.05
repeat-penalty = 1.0
spec-type = draft-mtp
spec-draft-n-max = 2
spec-draft-p-min = 0.5
np = 1
batch-size = 2048
ubatch-size = 1024

[qwen3.6-27b-ud-q4-k-xl-vision]
model = /models/Qwen3.6-27B-UD-Q4_K_XL.gguf
mmproj = /models/Qwen3.6-27B-UD-Q4_K_XL-mmproj-BF16.gguf
jinja = true
chat-template-file = /chat-templates/qwen3.6-v20.jinja
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.05
repeat-penalty = 1.0
spec-type = draft-mtp
spec-draft-n-max = 2
spec-draft-p-min = 0.5
np = 1
batch-size = 2048
ubatch-size = 1024

[qwen3.6-35b-a3b]
model = /models/Qwen3.6-35B-A3B-UD-Q5_K_M.gguf
mmproj = /models/Qwen3.6-35B-A3B-mmproj-BF16.gguf
jinja = true
chat-template-file = /chat-templates/qwen3.6-v20.jinja
temp = 0.7
top-p = 0.8
top-k = 20
min-p = 0.0
repeat-penalty = 1.0
batch-size = 2048
ubatch-size = 1024
n-cpu-moe = 15

[gemma-4-e4b]
model = /models/gemma-4-E4B-it-UD-Q8_K_XL
mmproj = /models/gemma4-e4b-mmproj-bf16.gguf
jinja = true
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05
repeat-penalty = 1.0
batch-size = 2048
ubatch-size = 1024

[gemma-4-26b-a4b]
model = /models/gemma-4-26B-A4B-it-UD-Q5_K_M.gguf
mmproj = /models/gemma-4-26B-A4B-it-mmproj-F16.gguf
jinja = true
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05
repeat-penalty = 1.0
batch-size = 2048
ubatch-size = 1024
n-cpu-moe = 15

[gemma-4-31b]
model = /models/gemma-4-31B-it-Q5_K_M.gguf
jinja = true
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05
repeat-penalty = 1.0
batch-size = 2048
ubatch-size = 1024