[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#cc6666"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#cc6666"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#263748"
foreground = "#e6e6e6"

[font]
size = 10.0

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[font.normal]
family = "HackNerdFont"
style = "Regular"

[window.padding]
x = 5
y = 5
